
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 08 18:40:27 CST 2017
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int div = 5;
  public static final int suma = 2;
  public static final int num = 8;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int error = 1;
  public static final int por = 4;
  public static final int parc = 7;
  public static final int para = 6;
}

